### ISSUE TITLE
Is it possible to speed up the runtime of goversioninfo?

### ISSUE THREAD

**Issue by tomasz1986** [josephspurrier/goversioninfo#48]
Please forgive me if this is not the right place for the question.

I build [Syncthing](https://github.com/syncthing/syncthing) executables for Windows on a regular basis, and running `goversioninfo` takes as much as 50s out of the 60s-long process (see https://forum.syncthing.net/t/16302/8 for details). I am wondering whether there is anything that could be done to speed up the whole process. If I skip the execution of `goversioninfo`, the compilation times drops to just a few seconds, so there is a huge difference between using and not using it :pensive:.

**Comment by tc-hib** [comment]
@tomasz1986 
I can't reply in that forum because I'm a new user and I have replied 3 times already 🙄 
But you should tell them that I was wrong, rsrc does not seem to be fixed.

I tried it, and it does take several seconds where it should be instant, and it still produces an invalid .rsrc section, though Explorer is fault-tolerant enough for it.

You can easily compare it by running the following:

```
go install github.com/akavel/rsrc@latest
rsrc -ico logo.ico
go install github.com/tc-hib/go-winres@latest
go-winres simply --icon logo.ico
```

What's strange is that rsrc now produces a file that's not aligned but much bigger. It should only be slightly bigger than `logo.ico`.

**Comment by tomasz1986** [comment]
Hmm, but the slow builds have fixed themselves after I upgraded to the newest Go, so the original issue is not really valid anymore.

I would personally suggest that you open an issue on the Syncthing's GitHub (or a new thread on the forum) about the other problems with the resulting `syncthing.exe` binary. I will close this one, as the slowness itself is gone now.
